### ISSUE TITLE
Code Run Error

### ISSUE THREAD

**Issue by XRui-Y** [GeoDS/CATS#1] opened 2024-03-14 13:54 UTC
Dear Author:
The error "ValueError: cannot reshape array of size 393200 into shape (24,128,128)" occurs when I run run_cats.py. I suspect it's related to the spatiotemporal mobility matrix npy files. However, you only provided k-anonymized aggregated spatiotemporal mobility matrix data files. When I modify [--img_path] to this file path, I encounter the above error. I would greatly appreciate it if you could help me clarify this issue. Thank you.

**Comment by PhanTask** [comment] 2024-03-18 05:05
Hi, thank you for your interest in our work. I attempted to reproduce the issue by cloning the repo and running run_cats.py, but I did not encounter this issue. Here are a few options for debugging:
1. Double check if your downloaded matrix data files are complete.
2. Double check if there is a dependency library version mismatch.

Also, due to our signed NDA, we are not able to release the original individual data and its derivatives (e.g., training weights). You may process other data into the required format to try training and inference.

**Comment by XRui-Y** [comment] 2024-03-18 05:26
> 您好，感谢您对我们工作的兴趣。我尝试通过克隆存储库并运行 run_cats.py 来重现该问题，但没有遇到此问题。以下是一些调试选项：
> 
> 1. 仔细检查您下载的矩阵数据文件是否完整。
> 2. 仔细检查是否存在依赖库版本不匹配的情况。
> 
> 此外，由于我们签署了保密协议，我们无法发布原始个人数据及其衍生数据（例如训练权重）。您可以将其他数据处理成所需的格式以尝试训练和推理。

Thank you for your answer.

**Comment by XRui-Y** [comment] 2024-03-18 05:31
> Hi, thank you for your interest in our work. I attempted to reproduce the issue by cloning the repo and running run_cats.py, but I did not encounter this issue. Here are a few options for debugging:
> 
> 1. Double check if your downloaded matrix data files are complete.
> 2. Double check if there is a dependency library version mismatch.
> 
> Also, due to our signed NDA, we are not able to release the original individual data and its derivatives (e.g., training weights). You may process other data into the required format to try training and inference.



> Hi, thank you for your interest in our work. I attempted to reproduce the issue by cloning the repo and running run_cats.py, but I did not encounter this issue. Here are a few options for debugging:
> 
> 1. Double check if your downloaded matrix data files are complete.
> 2. Double check if there is a dependency library version mismatch.
> 
> Also, due to our signed NDA, we are not able to release the original individual data and its derivatives (e.g., training weights). You may process other data into the required format to try training and inference.

Thank you for your response. I also sent you an email earlier asking about some questions regarding LSTM-trajGan. I would greatly appreciate it if you could kindly provide me with some guidance whenever it's convenient for you. Thank you very much

**Comment by PhanTask** [comment] 2024-03-19 08:01
@W-monster I have replied your email. I am closing this issue if no more related questions. For the discussion about LSTM-TrajGAN please open issues in its repo.

**Closed as completed by PhanTask** 2024-03-19 08:01 UTC
